import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Copy, Pencil, Plus, Trash2, Target, ArrowUpRight } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useCriteria, useIcps, useInvalidate } from "@/lib/queries";
import { currentUserId } from "@/lib/session";
import type { Icp } from "@/lib/types";
import { parseQualificationRules, serializeQualificationRules, type IcpQualificationRule, type QualificationMode, type QualificationOperator, type QualificationSignal } from "@/services/prospectingService";

export const Route = createFileRoute("/_authenticated/icps")({ head: () => ({ meta: [{ title: "Perfis de cliente ideal (ICP) — ProspectFlow" }, { name: "robots", content: "noindex" }] }), component: IcpsPage });
type IcpForm = Partial<Icp> & { keywordsText?: string; qualificationRules?: IcpQualificationRule[]; notesText?: string };
const RULE_LABELS: Record<QualificationSignal, string> = { website: "Tem site", landing_page: "Tem landing page", instagram: "Tem Instagram", meta_ads: "Já anuncia no Meta Ads", google_ads: "Já anuncia no Google Ads" };
const PRESETS: Record<string, { label: string; rules: IcpQualificationRule[] }> = {
  landing_page: { label: "Vender Landing Page", rules: [{ signal: "website", operator: "not_has", mode: "required", weight: 25 }, { signal: "landing_page", operator: "not_has", mode: "preferred", weight: 20 }] },
  traffic_meta: { label: "Vender tráfego Meta", rules: [{ signal: "meta_ads", operator: "has", mode: "preferred", weight: 25 }, { signal: "website", operator: "has", mode: "preferred", weight: 10 }, { signal: "instagram", operator: "has", mode: "preferred", weight: 10 }] },
  traffic_google: { label: "Vender tráfego Google", rules: [{ signal: "google_ads", operator: "has", mode: "preferred", weight: 25 }, { signal: "website", operator: "has", mode: "preferred", weight: 10 }] },
  social: { label: "Vender social media", rules: [{ signal: "instagram", operator: "not_has", mode: "required", weight: 25 }, { signal: "website", operator: "has", mode: "preferred", weight: 10 }] },
};
function parseNotes(value: string | null | undefined) { if (!value) return ""; try { const parsed = JSON.parse(value) as { notes?: string }; return typeof parsed.notes === "string" ? parsed.notes : value; } catch { return value; } }
function ruleKey(rule: IcpQualificationRule) { return `${rule.signal}:${rule.operator}`; }

function IcpsPage() {
  const invalidate = useInvalidate(); const { data: icps = [], isLoading } = useIcps(); const { data: criteria = [] } = useCriteria(); const [editing, setEditing] = useState<IcpForm | null>(null); const [saving, setSaving] = useState(false);
  function openNew() { setEditing({ name: "", requires_website: false, requires_instagram: false, keywordsText: "", qualificationRules: [], notesText: "" }); }
  function openEdit(icp: Icp) { setEditing({ ...icp, keywordsText: (icp.keywords ?? []).join(", "), qualificationRules: parseQualificationRules(icp.other_criteria), notesText: parseNotes(icp.other_criteria) }); }
  const save = async () => { if (!editing) return; const name = (editing.name ?? "").trim(); if (!name) return void toast.error("Dê um nome ao ICP."); setSaving(true); try { const userId = await currentUserId(); const rules = editing.qualificationRules ?? []; const payload = { user_id: userId, name, niche: editing.niche ?? null, subniche: editing.subniche ?? null, city: editing.city ?? null, state: editing.state ?? null, regions: editing.regions ?? null, country: editing.country ?? "BR", revenue_min: editing.revenue_min ?? null, revenue_max: editing.revenue_max ?? null, employees_min: editing.employees_min ?? null, employees_max: editing.employees_max ?? null, keywords: (editing.keywordsText ?? "").split(",").map((k) => k.trim()).filter(Boolean), requires_website: editing.requires_website ?? false, requires_instagram: editing.requires_instagram ?? false, other_criteria: serializeQualificationRules(rules, editing.notesText ?? "") }; const { error } = editing.id ? await supabase.from("icps").update(payload).eq("id", editing.id) : await supabase.from("icps").insert(payload); if (error) throw new Error(error.message); toast.success("ICP salvo."); setEditing(null); invalidate(["icps"]); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro ao salvar ICP."); } finally { setSaving(false); } };
  async function duplicate(icp: Icp) { try { const userId = await currentUserId(); const { id: _id, created_at: _c, updated_at: _u, ...rest } = icp; const { error } = await supabase.from("icps").insert({ ...rest, user_id: userId, name: `${icp.name} (cópia)` }); if (error) throw new Error(error.message); invalidate(["icps"]); toast.success("ICP duplicado."); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro ao duplicar."); } }
  async function remove(id: string) { const { error } = await supabase.from("icps").delete().eq("id", id); if (error) toast.error("Não foi possível excluir."); else { invalidate(["icps"]); toast.success("ICP excluído."); } }
  async function setWeight(id: string, weight: number) { const { error } = await supabase.from("icp_criteria").update({ weight }).eq("id", id); if (error) toast.error("Não foi possível salvar o peso."); else invalidate(["icp_criteria"]); }
  const setRule = (index: number, patch: Partial<IcpQualificationRule>) => { if (!editing?.qualificationRules) return; setEditing({ ...editing, qualificationRules: editing.qualificationRules.map((rule, i) => i === index ? { ...rule, ...patch } : rule) }); };
  const toggleRule = (signal: QualificationSignal) => { if (!editing) return; const current = editing.qualificationRules ?? []; const existingIndex = current.findIndex((rule) => rule.signal === signal); if (existingIndex >= 0) setEditing({ ...editing, qualificationRules: current.filter((_, i) => i !== existingIndex) }); else setEditing({ ...editing, qualificationRules: [...current, { signal, operator: "has", mode: "preferred", weight: 10 }] }); };
  const applyPreset = (rules: IcpQualificationRule[]) => { if (editing) setEditing({ ...editing, qualificationRules: rules.map((rule) => ({ ...rule })) }); };

  return <div className="space-y-7">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Qualificação</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">ICPs</h1><p className="mt-1.5 text-sm text-muted-foreground">Perfis que orientam sua busca e ajudam a priorizar os prospects certos.</p></div><Button onClick={openNew}><Plus className="mr-2 size-4" />Novo ICP</Button></header>
    {isLoading ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-48 rounded-2xl" />)}</div> : !icps.length ? <div className="glass rounded-2xl border-dashed p-10 text-center"><Target className="mx-auto size-8 text-primary/60" /><p className="mt-3 font-medium">Nenhum ICP ainda</p><p className="mt-1 text-sm text-muted-foreground">Crie seu primeiro perfil para começar a prospectar.</p><Button className="mt-5" onClick={openNew}>Criar primeiro ICP</Button></div> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{icps.map((icp) => <article key={icp.id} className="interactive-card glass flex flex-col gap-4 rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Target className="size-4" /></span><h2 className="truncate font-semibold">{icp.name}</h2></div><p className="mt-2 text-xs text-muted-foreground">{[icp.niche, icp.subniche].filter(Boolean).join(" · ") || "Sem nicho definido"}</p></div><div className="flex shrink-0 gap-1"><Button variant="ghost" size="icon" className="size-8" aria-label="Editar" onClick={() => openEdit(icp)}><Pencil className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-8" aria-label="Duplicar" onClick={() => void duplicate(icp)}><Copy className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-8 text-muted-foreground hover:text-destructive" aria-label="Excluir" onClick={() => void remove(icp.id)}><Trash2 className="size-3.5" /></Button></div></div><div className="grid grid-cols-2 gap-2 rounded-xl bg-muted/40 p-3 text-xs"><div><span className="text-muted-foreground">Local</span><p className="mt-1 font-medium">{[icp.city, icp.state, icp.regions].filter(Boolean).join(", ") || "Qualquer região"}</p></div><div><span className="text-muted-foreground">Porte</span><p className="mt-1 font-medium">{icp.employees_min || icp.employees_max ? `${icp.employees_min ?? 0}–${icp.employees_max ?? "∞"} pessoas` : "Não definido"}</p></div></div><div className="flex min-h-12 flex-wrap content-start gap-1">{(icp.keywords ?? []).slice(0, 5).map((k) => <Badge key={k} variant="secondary" className="rounded-full">{k}</Badge>)}{parseQualificationRules(icp.other_criteria).slice(0, 2).map((rule) => <Badge key={ruleKey(rule)} variant="outline" className="rounded-full">{rule.operator === "has" ? "Tem" : "Não tem"} {RULE_LABELS[rule.signal]}</Badge>)}</div><div className="mt-auto flex items-center justify-between border-t border-border/60 pt-3 text-xs text-muted-foreground"><span>{icp.requires_website || icp.requires_instagram ? "Critérios digitais ativos" : "Critérios básicos"}</span><span className="inline-flex items-center font-semibold text-primary">Editar <ArrowUpRight className="ml-1 size-3.5" /></span></div></article>)}</div>}
    <section className="space-y-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Pontuação</p><h2 className="mt-1 text-xl font-semibold">Critérios do ICP Score</h2><p className="mt-1 text-sm text-muted-foreground">Ajuste o peso de cada critério de qualificação.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{criteria.map((c) => <div key={c.id} className="glass interactive-card flex items-center gap-3 rounded-xl p-3"><div className="grid size-8 place-items-center rounded-lg bg-primary/10 text-xs font-bold text-primary">{Math.round(Number(c.weight))}</div><Label htmlFor={`w-${c.id}`} className="flex-1 text-sm">{c.label}</Label><Input id={`w-${c.id}`} type="number" min={0} max={100} defaultValue={c.weight} onBlur={(e) => void setWeight(c.id, Number(e.target.value))} className="w-20" /></div>)}</div></section>
    <Sheet open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{editing?.id ? "Editar ICP" : "Novo ICP"}</SheetTitle></SheetHeader>{editing && <div className="mt-4 space-y-5 px-4 pb-8">{[
      ["Identidade", <><Field label="Nome" value={editing.name ?? ""} onChange={(v) => setEditing({ ...editing, name: v })} /><div className="mt-3 grid grid-cols-2 gap-3"><Field label="Nicho" value={editing.niche ?? ""} onChange={(v) => setEditing({ ...editing, niche: v })} /><Field label="Subnicho" value={editing.subniche ?? ""} onChange={(v) => setEditing({ ...editing, subniche: v })} /></div></>],
      ["Localização e porte", <><div className="grid grid-cols-2 gap-3"><Field label="Cidade" value={editing.city ?? ""} onChange={(v) => setEditing({ ...editing, city: v })} /><Field label="Estado" value={editing.state ?? ""} onChange={(v) => setEditing({ ...editing, state: v })} /></div><div className="mt-3"><Field label="Regiões" value={editing.regions ?? ""} onChange={(v) => setEditing({ ...editing, regions: v })} /></div><div className="mt-3 grid grid-cols-2 gap-3"><Field label="Faturamento mínimo" type="number" value={editing.revenue_min?.toString() ?? ""} onChange={(v) => setEditing({ ...editing, revenue_min: v ? Number(v) : null })} /><Field label="Faturamento máximo" type="number" value={editing.revenue_max?.toString() ?? ""} onChange={(v) => setEditing({ ...editing, revenue_max: v ? Number(v) : null })} /><Field label="Funcionários mín." type="number" value={editing.employees_min?.toString() ?? ""} onChange={(v) => setEditing({ ...editing, employees_min: v ? Number(v) : null })} /><Field label="Funcionários máx." type="number" value={editing.employees_max?.toString() ?? ""} onChange={(v) => setEditing({ ...editing, employees_max: v ? Number(v) : null })} /></div></>],
    ].map(([title, content]) => <section key={String(title)} className="rounded-xl border border-border/70 bg-muted/20 p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-primary">{title}</p><div className="mt-3">{content}</div></section>)}
      <Field label="Palavras-chave (separadas por vírgula)" value={editing.keywordsText ?? ""} onChange={(v) => setEditing({ ...editing, keywordsText: v })} />
      <section className="space-y-3 rounded-xl border border-border/70 bg-muted/20 p-4"><div><Label>Presets de oferta</Label><p className="text-xs text-muted-foreground">Use uma lógica pronta e ajuste depois.</p></div><div className="grid grid-cols-2 gap-2">{Object.entries(PRESETS).map(([key, preset]) => <Button key={key} type="button" variant="outline" className="justify-start gap-2 bg-background/60 text-left" onClick={() => applyPreset(preset.rules)}><Target className="size-4 shrink-0" />{preset.label}</Button>)}</div></section>
      <section className="space-y-3 rounded-xl border border-border/70 bg-muted/20 p-4"><div><Label>Critérios de qualificação</Label><p className="text-xs text-muted-foreground">Escolha os sinais digitais que entram na filtragem.</p></div>{(["website","landing_page","instagram","meta_ads","google_ads"] as QualificationSignal[]).map((signal) => { const index = (editing.qualificationRules ?? []).findIndex((r) => r.signal === signal); const rule = index >= 0 ? editing.qualificationRules![index] : null; return <div key={signal} className="rounded-xl bg-background/65 p-3"><div className="flex items-center gap-3"><Switch checked={Boolean(rule)} onCheckedChange={() => toggleRule(signal)} /><span className="flex-1 text-sm font-medium">{RULE_LABELS[signal]}</span>{rule && <Input className="w-20" type="number" min={0} max={100} value={rule.weight} onChange={(e) => setRule(index, { weight: Number(e.target.value) })} />}</div>{rule && <div className="mt-2 grid grid-cols-2 gap-2"><select className="h-9 rounded-md border border-input bg-background px-2 text-sm" value={rule.operator} onChange={(e) => setRule(index, { operator: e.target.value as QualificationOperator })}><option value="has">Tem</option><option value="not_has">Não tem</option></select><select className="h-9 rounded-md border border-input bg-background px-2 text-sm" value={rule.mode} onChange={(e) => setRule(index, { mode: e.target.value as QualificationMode })}><option value="required">Obrigatório</option><option value="preferred">Priorizar</option></select></div>}</div>; })}</section>
      <div className="grid gap-3 sm:grid-cols-2"><div className="flex items-center justify-between rounded-xl border border-border/70 bg-muted/20 p-3"><Label htmlFor="req-site">Site obrigatório</Label><Switch id="req-site" checked={Boolean(editing.requires_website)} onCheckedChange={(v) => setEditing({ ...editing, requires_website: v })} /></div><div className="flex items-center justify-between rounded-xl border border-border/70 bg-muted/20 p-3"><Label htmlFor="req-ig">Instagram obrigatório</Label><Switch id="req-ig" checked={Boolean(editing.requires_instagram)} onCheckedChange={(v) => setEditing({ ...editing, requires_instagram: v })} /></div></div>
      <div className="space-y-1.5"><Label htmlFor="other">Observações</Label><Textarea id="other" value={editing.notesText ?? ""} onChange={(e) => setEditing({ ...editing, notesText: e.target.value })} placeholder="Ex.: equipe comercial própria, atende alto ticket..." /></div><Button onClick={() => void save()} disabled={saving} className="sticky bottom-0 w-full rounded-xl shadow-lg">{saving ? "Salvando..." : "Salvar ICP"}</Button>
    </div>}</SheetContent></Sheet>
  </div>;
}
interface FieldProps { label: string; value: string; type?: string; onChange: (value: string) => void; }
function Field({ label, value, type = "text", onChange }: FieldProps) { const id = label.toLowerCase().replace(/[^a-z]+/g, "-"); return <div className="space-y-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
